# Generated by Django 3.2.4 on 2023-08-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pprice', models.CharField(max_length=15)),
                ('dprice', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('pcolor', models.CharField(max_length=15)),
            ],
        ),
    ]
