# Generated by Django 3.2.4 on 2023-08-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='mcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='pcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.mcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='pdesc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default=True, upload_to='static/product'),
        ),
    ]
