# Generated by Django 3.2.4 on 2023-08-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230821_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=25)),
                ('Mob', models.IntegerField(max_length=11)),
                ('Email', models.EmailField(max_length=25)),
                ('Password', models.IntegerField(max_length=16)),
            ],
        ),
    ]
