# Generated by Django 3.2.4 on 2023-08-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AlterField(
            model_name='register',
            name='Email',
            field=models.EmailField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='Mob',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='Password',
            field=models.IntegerField(),
        ),
    ]
