# Generated by Django 3.2.4 on 2023-09-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='maincategory',
        ),
        migrations.AddField(
            model_name='product',
            name='macategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.maincategory'),
        ),
    ]
