# Generated by Django 3.2.4 on 2023-09-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230906_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
